Rnorm
nataliecrowe060/Methane-NCrowe pull request #6
Opened 2022-06-18 21:35 UTC by nataliecrowe060

My Saturday work- both some tests in another file and the main markdown file with an added histogram/rnorm run and a change to the sensitivity analysis.

2022-06-20 08:08 UTC, bpbond requested changes
Nice work @nataliecrowe060

2022-06-20 08:08 UTC, bpbond commented on Methane_MarkDown.Rmd
> +Once we have our differing parameter values we can create a graph. Using the graph function `facet_wrap`to separate the results based on variable.
"Once we have our model outputs we can..."

2022-06-20 08:08 UTC, bpbond commented on Methane_MarkDown.Rmd
> +firstValue <- x * (1 - 0.2)
`ch4_low` and `ch4_high` would be more descriptive names.

2022-06-20 08:08 UTC, bpbond commented on Methane_MarkDown.Rmd
> +  labs( x= "Natural CH4 Level", y= "count", main= "Natural CH4 Histogram")
What are the units of the x axis?

2022-06-20 08:08 UTC, bpbond commented on Methane_MarkDown.Rmd
> +To examine SSP245's Natural methane  sensitivity we first ask hector to fetch the data. We then create a function to run our parameter set to a particular value. In this case we set our value at `358
>we first ask hector to fetch the data

What data? 😕

2022-06-20 08:08 UTC, bpbond commented on Methane_MarkDown.Rmd
> +paramr<- fetchvars(core, NA, NATURAL_CH4())
Maybe use a more descriptive name, e.g. `default`?

2022-06-20 08:08 UTC, bpbond commented on Methane_MarkDown.Rmd
> +sensitivity_emission <- run_with_param_range(core, NATURAL_CH4(), seq(firstValue, lastValue, 5))
You may want to do
```r
ch4_seq <- seq(firstValue, lastValue, 5)
sensitivity_emission <- run_with_param_range(core, NATURAL_CH4(), ch4_seq)
```
...and then use `ch4_seq` for your graph below.

2022-06-20 08:08 UTC, bpbond commented on Methane_MarkDown.Rmd
> +Using the same `Natural_CH4` data, we can also make a histogram plot. First we use `rnorm` to set a `mean=` to the constant( 341Tg ) and a `sd` of the constant multiplied by `0.2`.
Since you say "using the same data", I would use `ch4_seq` (see above) for your graph.

2022-06-21 12:44 UTC, leeyap approved these changes
Great job!

2022-06-30 14:57 UTC, merged